<!DOCTYPE html>
<html lang="fr">
<head>
 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width", initial-scale=1, scalable="yes" />
    <link rel="stylesheet" type="text/css" href="header.css">
    <link rel="stylesheet" type="text/css" href="soft-menu12.css">
    <title>Autosma Welcome Page</title>
<style type="text/css">


</style>
</head>

<body>

<header>    
<center><div>
    <table class="headertable"><tr>
    <th style="width: 20px"><div id="google_translate_element2"><div class="skiptranslate goog-te-gadget" dir="ltr"><div class="divlang" id=":0.targetLanguage">
        <select name="Lang" class="goog-te-combo" aria-label="Widget de traduction" bgcolor="green" id="Lang" >
            <option value="">Choix de langue</option>
            <option value="fr" selected="Français">Français</option>
            <option value="de">Allemand</option>
            <option value="en">Anglais</option>
            <option value="es">Espagnol</option>
        </select>&nbsp;<span style="white-space:nowrap">
            <a href="https://translate.google.com/" target="_blank"></a></span></div></div></th>
<th class="welcome1"><a class="wel-ref1" href="welcome3.php"> BIENVENUE DANS AUTOSMA</a></th>
<th class="th-cookies">
    <div class="div-cookies">Bienvenue Adrian</div></th>
    <th>
    <div class="logout"><a class="ref-logout" href="index.php" ><img class="inout" src="images/onof.png" /></a></div>
        </th>
</tr></table></center>
</div>
<div>
    
    <nav><input type="checkbox" id="menu-mobile" role="button">

        <label for="menu-mobile" class="menu-mobile">Menu</label>
        <input type="checkbox" id="menu-mobile" role="button" />
<ul class="ul-menu-1">
    
    <li class="insc"><a class="menu-ref" href="inscription.php">INSCRIPTION</a></li>
    <li class="ele"><a class="menu-ref" href="eleves.php">ELEVES</a> </li>

    <li class="solva"><a class="menu-ref" href="solvable.php">SOLVABILITER</a></li>
    
    <li class="class"><a class="menu-ref" href="prof.php">PROFESSEUR / ENSEIGNANT</a></li>
    
    <li class="class"><a class="menu-ref" href="COURS.PHP">COURS</a></li>

    <li class="class"><a class="menu-ref" href="Class.php">CLASSES</a></li>

    <li class="class"><a class="menu-ref" href="horaire.php">HORAIRES</a></li>

    <li class="inf"><a class="menu-ref" href="infos.php">INFORMATIONS</a></li>

    </li>

    </ul>
</nav>
</div></ul><div class="date-div">
     <?php
include('date.php');
?>
</div>
</nav>   
  </header>   
</body>
</html>
